# Generated by Django 6.0.3 on 2026-03-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
    ]
