# Generated by Django 6.0.3 on 2026-05-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
