services:

  db:
    image: postgres:15
    container_name: jobportal_postgres_db
    restart: always
    environment:
      POSTGRES_DB: jobportal_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    build: .
    container_name: django_jobportal_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db

volumes:
  postgres_data: